include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-docker.yml'

variables:
  EICAR_EXE_URL: https://secure.eicar.org/eicar.com
  EICAR_TXT_URL: https://secure.eicar.org/eicar.com.txt
  EICAR_ZIP_URL: https://secure.eicar.org/eicar_com.zip
  FF_NETWORK_PER_BUILD: "true"

.standalone:
  image:
    name: $CONTAINER_TEST_IMAGE
  dependencies: []
  variables:
    GIT_STRATEGY: none

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean
  
EXE Virus:
  stage: Test
  extends: .standalone
  script:
    - wget -O /tmp/eicar $EICAR_EXE_URL
    - clamdscan /tmp/eicar || code=$?; if [ $code -eq 1 ]; then echo "Detection OK"; else exit $code; fi

TXT Virus:
  stage: Test
  extends: .standalone
  script:
    - wget -O /tmp/eicar $EICAR_TXT_URL
    - clamdscan /tmp/eicar || code=$?; if [ $code -eq 1 ]; then echo "Detection OK"; else exit $code; fi

ZIP Virus:
  stage: Test
  extends: .standalone
  script:
    - wget -O /tmp/eicar $EICAR_ZIP_URL
    - clamdscan /tmp/eicar || code=$?; if [ $code -eq 1 ]; then echo "Detection OK"; else exit $code; fi
